using Helpers.SourceGenerator.Attributes;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Helpers.SourceGenerator.Generators;

[Generator(LanguageNames.CSharp)]
public class MappingGenerator : IIncrementalGenerator
{
    private static readonly List<string> MappedClassNames = [];
    private const string TAB = "    "; // not the best way, but I find it funny to read

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsCandidate(s),
                transform: static (ctx, _) => GetSemanticTarget(ctx))
            .Where(static m => m != default)!;

        context.RegisterSourceOutput(classDeclarations, static (spc, classWithMaps) =>
        {
            GenerateMapping(spc, classWithMaps.classSymbol!, classWithMaps.maps!);
        });
    }

    private static bool IsCandidate(SyntaxNode node) =>
        node is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0;

    private static (INamedTypeSymbol? classSymbol, IEnumerable<INamedTypeSymbol>? maps) GetSemanticTarget(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
        if (symbol == null) return default;

        var mappedAttr = context.SemanticModel.Compilation
            .GetTypeByMetadataName(typeof(MappedAttribute).FullName);

        if (mappedAttr == null) return default;

        var classSymbol = symbol.GetAttributes().Any(a =>
            SymbolEqualityComparer.Default.Equals(a.AttributeClass, mappedAttr))
            ? symbol
            : null;

        if (classSymbol == null) return default;

        var maps = symbol.GetAttributes()
            .Where(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, mappedAttr))
            .SelectMany(a =>
                a.ConstructorArguments.Select(ca => ca)
                 .Concat(a.NamedArguments.Select(na => na.Value))
                 .Distinct()
            )
            .Where(tc => tc.Kind == TypedConstantKind.Type && tc.Value is INamedTypeSymbol)
            .Select(tc => (INamedTypeSymbol)tc.Value!)
            .ToList();

        if (maps?.Count is null or 0) return default;

        MappedClassNames.Add(classSymbol.Name);
        return (classSymbol, maps);
    }

    private static void GenerateMapping(SourceProductionContext context, 
        INamedTypeSymbol classSymbol, IEnumerable<INamedTypeSymbol> maps)
    {
        var ns = classSymbol.ContainingNamespace.ToDisplayString();
        var namespaces = new HashSet<string>
        {
            "System.Collections.Generic",
            "System.Linq"
        };
        foreach (var map in maps)
        {
            namespaces.Add(map.ContainingNamespace.ToDisplayString());
        }

        var className = classSymbol.Name;
        var props = classSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
            .ToList();

        var headerSb = new StringBuilder();
        headerSb.AppendLine("// <auto-generated>");
        headerSb.AppendLine($"// {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        headerSb.AppendLine("// </auto-generated>");
        headerSb.AppendLine();

        var sb = new StringBuilder();
        sb.AppendLine($"namespace {ns}.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"{TAB}public static class {className}Mapper");
        sb.AppendLine($"{TAB}{{");

        foreach (var map in maps)
        {
            var mapProperties = map.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic
                    && !p.IsAbstract && !p.IsReadOnly)
                .ToList()
                .Where(p => props.Select(pr => pr.Name).Contains(p.Name));

            sb.AppendLine($"{TAB}{TAB}public static {className} Map{map.Name}To{className}(this {map.Name} obj)");
            WriteExplicitMapping(props, sb, mapProperties, namespaces);
            sb.AppendLine();

            sb.AppendLine($"{TAB}{TAB}public static {map.Name} Map{className}To{map.Name}(this {className} obj)");
            WriteExplicitMapping(props, sb, mapProperties, namespaces);
            sb.AppendLine();

            sb.AppendLine($"{TAB}{TAB}public static IEnumerable<{map.Name}> Map{className}To{map.Name}(this IEnumerable<{className}> obj)");
            sb.AppendLine($"{TAB}{TAB}{TAB}=> obj.Where(o => o is not null).Select(Map{className}To{map.Name});");
            sb.AppendLine();

            sb.AppendLine($"{TAB}{TAB}public static IEnumerable<{className}> Map{map.Name}To{className}(this IEnumerable<{map.Name}> obj)");
            sb.AppendLine($"{TAB}{TAB}{TAB}=> obj.Where(o => o is not null).Select(Map{map.Name}To{className});");
        }

        sb.AppendLine($"{TAB}}}");
        sb.AppendLine("}");

        foreach (var import in namespaces)
        {
            headerSb.AppendLine($"using {import};");
        }
        headerSb.AppendLine();
        headerSb.Append(sb.ToString());

        context.AddSource($"{className}Mapper.Incremental.g.cs", SourceText.From(headerSb.ToString(), Encoding.UTF8));
    }

    private static void WriteExplicitMapping(List<IPropertySymbol> props, StringBuilder sb, 
        IEnumerable<IPropertySymbol> mapProperties, HashSet<string> ns)
    {
        sb.AppendLine($"{TAB}{TAB}{{");
        sb.AppendLine($"{TAB}{TAB}{TAB}return new()");
        sb.AppendLine($"{TAB}{TAB}{TAB}{{");
        foreach (var prop in mapProperties)
        {
            if (prop.Type.TypeKind is TypeKind.Class or TypeKind.Interface
                && prop.Type.Name != props.First(p => p.Name == prop.Name).Type.Name)
            {
                if (!MappedClassNames.Contains(prop.Type.Name)) continue;

                // FIXME
                ns.Add(prop.Type.ContainingNamespace.ToDisplayString());
                sb.AppendLine($"{TAB}{TAB}{TAB}{TAB}{prop.Name} = obj.{prop.Name} != null ? obj.{prop.Name}.Map{prop.Type.Name}To{prop.Type.Name}() : null,");
            }
            else
            {
                sb.AppendLine($"{TAB}{TAB}{TAB}{TAB}{prop.Name} = obj.{prop.Name},");
            }
        }
        sb.AppendLine($"{TAB}{TAB}{TAB}}};");
        sb.AppendLine($"{TAB}{TAB}}}");
    }
}